---
- name: provision virtual machine
  azure_rm_virtualmachine:
    name: "{{ item }}"
    resource_group: "{{ resource_group_name }}"
    os_type: Windows
    managed_disk_type: "Standard_LRS"    
    admin_username: "{{ admin_name}}"
    admin_password: "{{ vm_password }}"
    image:
      offer: "{{ os_type }}"
      publisher: "{{ os_publisher }}"
      sku: "{{ os_sku }}"
      version: "{{ os_version }}"
    vm_size: "{{ vm_type }}"
  with_items:
    - webappvm1
    - sqldbvm1
